all: clock drink
	g++ -pedantic-errors -g main.cpp drink clock -o main
clock: clock.cpp clock.h
	g++ -pedantic-errors -c -g clock.cpp -o clock
drink: drink.cpp drink.h
	g++ -pedantic-errors -c -g drink.cpp -o drink